services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:                # disable ports section when running with separate reverse proxy
      - "3010:8080"
    environment:
      - ADMINER_DESIGN=haeckel
      - ADMINER_DEFAULT_SERVER=timescaledb
    networks:
      - postgres

networks:
  postgres:
    external: true
