{
 "title": "Simulator data",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM process_value_numeric_with_topic\r\nWHERE\r\n  (\r\n    topic = 'uns/v1/company/site/area/productionline/workcell/origin/pressure'\r\n    AND $__timeFilter(\"timestamp\")\r\n  )\r\nORDER BY \"timestamp\""
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM process_value_numeric_with_topic\r\nWHERE\r\n  (\r\n    topic = 'uns/v1/company/site/area/productionline/workcell/origin/humidity'\r\n    AND $__timeFilter(\"timestamp\")\r\n  )\r\nORDER BY \"timestamp\""
    }
   ]
  },
  {
   "title": "Airquality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM process_value_numeric_with_topic\r\nWHERE\r\n  (\r\n    topic = 'uns/v1/company/site/area/productionline/workcell/origin/airquality'\r\n    AND $__timeFilter(\"timestamp\")\r\n  )\r\nORDER BY \"timestamp\""
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM process_value_numeric_with_topic\r\nWHERE\r\n  (\r\n    topic = 'uns/v1/company/site/area/productionline/workcell/origin/temperature'\r\n    AND $__timeFilter(\"timestamp\")\r\n  )\r\nORDER BY \"timestamp\""
    }
   ]
  }
 ]
}