services:
  connect:
    image: redpandadata/connect:latest
    container_name: connect-factory1-to-global
    restart: always
    expose:
      - "4195"
    command: -c /config/pipeline.yml
    environment:
      KAFKA_BROKER: "redpanda:19092"
    volumes:
      - ./pipeline.yml:/config/pipeline.yml
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4195/ready"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kafka-global

networks:
  kafka-global:
    external: true