input:
  kafka:
    addresses:
      - ${KAFKA_BROKER}
    topics:
      - 'factory1'
    consumer_group: 'factory1-to-global'

#output:
#  stdout: {}

output:
  kafka:
    addresses:
      - ${KAFKA_BROKER}
    topic: 'global'
    key: ${!metadata("kafka_key")}
    #metadata:
    #  include_prefixes:
    #    - 'mqtt'
    #    - 'kafka'
    #    - 'uns'