services:
  connect:
    image: redpandadata/connect:latest
    container_name: connect-mqtt-to-kafka
    restart: always
    expose:
      - "4195"
    command: -c /config/pipeline.yml
    environment:
      MQTT_BROKER_LOCAL: "mosquitto:1883"
      KAFKA_BROKER_LOCAL: "redpanda-edge:9092"
    volumes:
      - ./pipeline.yml:/config/pipeline.yml
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4195/ready"]
    networks:
      - kafka-edge
      - mqtt

networks:
  kafka-edge:
    external: true
  mqtt:
    external: true
