input:
  mqtt:
    urls:
      - tcp://${MQTT_BROKER_LOCAL}
    client_id: "redpanda-connect-mqtt-to-kafka"
    connect_timeout: 30s
    topics:
      - '#'

pipeline:
  processors:
    - bloblang: |
        meta uns_timestamp_ms = timestamp_unix_milli()
        meta uns_origin = "factory1"

#output:
#  stdout: {}

output:
  kafka:
    addresses:
      - ${KAFKA_BROKER_LOCAL}
    topic: factory1
    key: ${!metadata("mqtt_topic")}

    #metadata:
    #  include_prefixes:
    #    - 'mqtt'
    #    - 'kafka'
    #    - 'uns'