services:
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: always
    ports:               # disable ports section, when running in edge+cloud mode, with separate reverse proxy
     - 1881:1880         #
    volumes:
      - /srv/unstack-data/nodered:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Europe/Berlin"
      NODE_RED_ENABLE_PROJECTS: true
    networks:
      - postgres
      - kafka-global
      #- reverseproxy    # only enable when running with separate reverse proxy
      #- mqtt            # only enable when running the reduced, combined-instance-mode

networks:
  postgres:
    external: true
  kafka-global:
    external: true
  #mqtt:
  #  external: true
  #reverseproxy:
  #  external: true
