services:
  nodered-global:
    container_name: nodered-global
    image: nodered/node-red:latest
    restart: always
    ports:               # disable ports section when running with separate reverse proxy
     - 1881:1880         #
    volumes:
      - /srv/unstack-data/nodered-global:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Europe/Berlin"
      NODE_RED_ENABLE_PROJECTS: true
    networks:
      - postgres
      - kafka-global

networks:
  postgres:
    external: true
  kafka-global:
    external: true
