input:
  mqtt:
    urls:
      - tcp://${!ENV:MQTT_BROKER_LOCAL}
      - tcp://host.docker.internal:1883
    client_id: "redpanda-connect-mqtt-to-kafka"
    connect_timeout: 30s
    topics:
      - '#'

pipeline:
  processors:
    - bloblang: |
        meta uns_timestamp_ms = timestamp_unix_milli()
        meta uns_origin = "factory1"

output:
  kafka:
    addresses:
      - ${!ENV:KAFKA_BROKER_LOCAL}
    topic: factory1
    key: ${!metadata("mqtt_topic")}
    #metadata:
    #  include_prefixes:.
    #    - 'mqtt'
    #    - 'kafka'
    #    - 'uns'