apiVersion: 1

datasources:
  - name: timescaledb
    type: postgres
    url: timescaledb:5432
    user: grafana
    secureJsonData:
      password: 'grafana'
    jsonData:
      database: unifiednamespace
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1700 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true
