services:
  nodered:
    container_name: nodered-edge
    image: nodered/node-red:latest
    restart: always
    ports:
      - 1880:1880
    volumes:
      - /srv/unstack-data/nodered-edge:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Europe/Berlin"
      NODE_RED_ENABLE_PROJECTS: true
    networks:
      - mqtt

networks:
  mqtt:
    external: true
