services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:             # enable ports section, when running without reverse proxy
      - 3000:3000      #
    user: '1000'
    env_file:
      - ../!credentials/credentials.env
    environment:
      GF_SERVER_ROOT_URL: ""   # only needed with reverse proxy
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - /srv/unstack-data/grafana:/var/lib/grafana
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
    networks:
      - postgres
      #- reverseproxy   # enable when running with a separate reverse proxy

networks:
  postgres:
    external: true
  #reverseproxy:
  #  external: true