services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:             # disable ports section, when running with reverse proxy
      - 3000:3000      #
    env_file:
      - .env
    environment:
      GF_SERVER_ROOT_URL: ""   # only needed with reverse proxy
      GF_SECURITY_ADMIN_USER: ${GRAFANA_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_SECURITY_ADMIN_PASSWORD}
    user: '1000'
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./config/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./dashboards:/var/lib/grafana/dashboards
      - /srv/unstack-data/grafana:/var/lib/grafana
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
    networks:
      - postgres

networks:
  postgres:
    external: true
