services:
  connect:
    image: redpandadata/connect:latest
    container_name: connect-kafka-to-cloud
    restart: always
    expose:
      - "4195"
    environment:
      KAFKA_BROKER_LOCAL: "redpanda-edge:9092"
      KAFKA_BROKER_UPSTREAM: "host.docker.internal:29092"  # change this, when running global stack on a separate host
    command: -c /config/pipeline.yml
    volumes:
      - ./pipeline.yml:/config/pipeline.yml
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4195/ready"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kafka-edge
      - kafka-global

networks:
  kafka-edge:
    external: true
  kafka-global:
    external: true
