services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    restart: always
    expose:
      - 5432
    env_file:
      - ../!credentials/credentials.env
    environment:
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      start_period: 20s
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d    # sql scripts that are run during database initialization
      - /srv/unstack-data/timescaledb/postgres:/var/lib/postgresql/data     # main postgres data directory
    networks:
      - postgres

networks:
  postgres:
    external: true
