services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    restart: always
    expose:
      - 5432
    env_file:
      - .env
    environment:
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      start_period: 20s
    volumes:
      - /srv/unstack-data/timescaledb/postgres:/var/lib/postgresql/data
      - ./db-init/100_create_grafana_user.sh:/docker-entrypoint-initdb.d/100_create_grafana_user.sh
      - ./db-init/101_create-tables.sql:/docker-entrypoint-initdb.d/101_create-tables.sql
      - ./db-init/102_create-views.sql:/docker-entrypoint-initdb.d/102_create-views.sql
    networks:
      - postgres

networks:
  postgres:
    external: true
